[theme]
primaryColor = "#1d4ed8"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#e2e8f0"
textColor = "#1e293b"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
